### PR TITLE
commandline integration

### PR DESCRIPTION
**Pull request by 4rz0**
Implemented simple commandline recognision.
Changed standard working directory to the one the jar is running in. (you may want to change that)
Possible commandline arguments: 
STANDARD for standard .minecraft folder
CURRENT for the folder the jar is running in
any absolute path to a .minecraft folder

### CODE REVIEW

**Comment by smbarbour** [comment]
Although that would certainly change the folder of where it changes the files, the Launch Minecraft button would not have the desired effect.  It launches the standard Minecraft Launcher which is hardcoded to the standard .minecraft folder.

**Comment by 4rz0** [comment]
Yea, i didn't take a look at that yet.
But i'm not using the standard launcher, anyways. I guess if someone really wants to change the folder, he isn't using the standard-launcher as well.
Maybe the button should be disabled when the working path is not standard.

**Comment by peerkoel** [comment]
This could work if the MCUpdater launches Minecraft in an AppletStub instead of a separate java process. Before starting the applet, use some reflexion to preset the first field which is a File to the path you want Minecraft to run in.

**Comment by smbarbour** [comment]
A big part of it is that the net.minecraft.client.Minecraft class has the path hardcoded as well.  That would have to be modified to allow it to work from another directory (which programs like MultiMC do).  MCUpdater is not a launcher however, and making that change is beyond the scope of this program.

**Comment by peerkoel** [comment]
Actually, I run Minecraft from different locations with a launcher that I patched in the way I described. At least 1.2.5 will run fine that way, not sure what 1.3 will do.
In net.minecraft.client.Minecraft there is a method that returns the base path which checks if a cached File member is null and if so it will determine the path and set the cached File. The trick I described presets the File member so that the standard base path is never determined and therefore never used.

**Comment by smbarbour** [comment]
We are going to implement something else instead.

**Pull request closed without merging**
